{{- if .Values.webhookCert.generate }}
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: {{ template "pravega-operator.fullname" . }}-issuer
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "pravega-operator.commonLabels" . | indent 4 }}
spec:
  ca:
    secretName: {{ template "pravega-operator.fullname" . }}-key-pair
{{- end }}
---
{{- if .Values.webhookCert.generate }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ template "pravega-operator.fullname" . }}-cert
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "pravega-operator.commonLabels" . | indent 4 }}
spec:
  isCA: true
  duration: 8760h
  renewBefore: 360h
  secretName: {{ template "pravega-operator.fullname" . }}-cert-tls
  commonName: pravega-webhook-svc.{{ .Release.Namespace }}.svc.cluster.local
  dnsNames:
    - pravega-webhook-svc
    - pravega-webhook-svc.{{ .Release.Namespace }}.svc.cluster.local
    - pravega-webhook-svc.{{ .Release.Namespace }}.svc
  issuerRef:
    name: {{ template "pravega-operator.fullname" . }}-issuer
{{- end }}
---
{{- if .Values.webhookCert.generate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pravega-operator.fullname" . }}-key-pair
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.webhookCert.crt }}
  tls.key: {{ .Values.webhookCert.key }}
{{- end }}
