apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "pravega-operator.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ template "pravega-operator.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ template "pravega-operator.fullname" . }}
        component: pravega-operator
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: {{ template "pravega-operator.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 6000
          name: metrics
        command:
        - pravega-operator
        {{- if .Values.testmode }}
        args: [-test]
        {{- end }}
        env:
        - name: WATCH_NAMESPACE
          value: "{{ .Values.watchNamespace }}"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: {{ template "pravega-operator.fullname" . }}
        volumeMounts:
        - name: webhook-cert
          mountPath: "/tmp/secret"
          readOnly: true
      volumes:
      - name: webhook-cert
        secret:
          secretName: selfsigned-cert-tls
