{{- if .Values.hooks.delete }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "pravega-operator.fullname" . }}-pre-delete
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation, hook-failed
rules:
- apiGroups:
  - pravega.pravega.io
  resources:
  - "*"
  verbs:
  - get
  - list
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "pravega-operator.fullname" . }}-pre-delete
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation, hook-failed
subjects:
  - kind: ServiceAccount
    name: {{ template "pravega-operator.fullname" . }}-pre-delete
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "pravega-operator.fullname" . }}-pre-delete
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "pravega-operator.fullname" . }}-pre-delete
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation, hook-failed

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pravega-operator.fullname" . }}-pre-delete
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation, hook-failed
data:
  pre-delete.sh: |
    #!/bin/sh
    exit_code=0
    echo "Checking for PravegaCluster Resource"

    ret=$(kubectl get PravegaCluster --all-namespaces --no-headers 2>&1)
    if (echo $ret | grep -e "No resources found" -e "the server doesn't have a resource type \"PravegaCluster\"" > /dev/null);
    then
      echo "None"
    else
      echo "$ret"
      exit_code=1
    fi

    if [ $exit_code -ne 0 ];
    then
      echo "Pre-delete Check Failed"
      exit $exit_code
    fi
    echo "Pre-delete Check OK"
---

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "pravega-operator.fullname" . }}-pre-delete
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation, hook-failed
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 20
  template:
    metadata:
      name: {{ template "pravega-operator.fullname" . }}-pre-delete
    spec:
      serviceAccountName: {{ template "pravega-operator.fullname" . }}-pre-delete
      restartPolicy: Never
      containers:
        - name: pre-delete-job
          image: "{{ .Values.hooks.image.repository }}:{{ .Values.hooks.image.tag }}"
          command:
            - /scripts/pre-delete.sh
          volumeMounts:
            - name: sh
              mountPath: /scripts
              readOnly: true
      volumes:
        - name: sh
          configMap:
            name: {{ template "pravega-operator.fullname" . }}-pre-delete
            defaultMode: 0555
{{- end }}
