apiVersion: v2
name: pravega
description: Pravega Helm chart for Kubernetes
version: 0.9.1
appVersion: 0.9.0
keywords:
- pravega
- storage
home: https://github.com/pravega/pravega
icon: https://avatars3.githubusercontent.com/u/25698199
