apiVersion: v1
kind: Service
metadata:
  name: pravega-webhook-svc
  namespace: default
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    component: pravega-operator
  sessionAffinity: None
  type: ClusterIP
---

apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: pravega-webhook-config
  annotations:
    cert-manager.io/inject-ca-from: default/selfsigned-cert
webhooks:
- clientConfig:
    service:
      name: pravega-webhook-svc
      namespace: default
      path: /validate-pravega-pravega-io-v1beta1-pravegacluster
  name: pravegawebhook.pravega.io
  failurePolicy: Fail
  rules:
  - apiGroups:
    - pravega.pravega.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pravegaclusters
    scope: "*"
  timeoutSeconds: 30
