apiVersion: v2
name: pravega-operator
description: Pravega Operator Helm chart for Kubernetes
version: 0.5.0
appVersion: 0.5.0
keywords:
- pravega
- storage
home: https://github.com/pravega/pravega-operator
icon: https://avatars3.githubusercontent.com/u/25698199
