apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "bookkeeper-operator.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ template "bookkeeper-operator.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ template "bookkeeper-operator.fullname" . }}
        component: bookkeeper-operator
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: {{ template "bookkeeper-operator.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 6000
          name: metrics
        command:
        - bookkeeper-operator
        {{- if .Values.testmode }}
        args: [-test]
        {{- end }}
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: {{ template "bookkeeper-operator.fullname" . }}
